services:
  grafana:
    image: grafana/grafana:11.6.0
    ports:
      - "3000:3000"
    volumes:
      - ./mounts/grafana:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admi
    restart: unless-stopped
  
  influxdb:
    image: influxdb:1.11
    volumes:
      - ./mounts/influx:/var/lib/influxdb
    restart: unless-stopped
  
  telegraf:
    image: telegraf:1.32
    volumes:
      - ./mounts/telegraf/telegraf.conf:/etc/telegraf/telegraf.conf:ro
    depends_on:
      - influxdb
    restart: unless-stopped
